apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - db-configmap.yaml
  - service.yaml
  - postgres-service.yaml
  - statefulset.yaml
  - managed-certificate.yaml
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
  - path: migration-job-patch.yaml
